---
title: "Sta 523 - Homework 6"
author: [Your names here]
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Setup

```{r message=FALSE}
# Load any necessary packages here
library(sf)
library(dplyr)
library(ggplot2)
library(readr)
library(stringr)
```

### Task 1 - Clean and Merge Data

#### Parking Violation Data

```{r message=FALSE}
if (!file.exists("nyc_parking.Rdata")) {
  nyc_raw = read_csv("/data/nyc_parking/NYParkingViolations.csv") 
  
  nyc = nyc_raw %>%
    setNames(str_replace_all(names(.)," ", "_")) %>%
    select(Violation_Precinct, House_Number, Street_Name) %>%
    transmute(precinct = Violation_Precinct, address = paste(House_Number, Street_Name)) %>%
    filter(address != "") %>%
    filter(precinct <= 34)
  
  save(nyc, file="nyc_parking.Rdata")
} else {
  load(file="nyc_parking.Rdata")
}
```

#### Geocoding Data

```{r warning=FALSE}
pluto = st_read("/data/nyc_parking/pluto_manhattan/MNMapPLUTO.shp", quiet=TRUE, stringsAsFactors = FALSE) 

pluto = pluto %>%
  st_geometry() %>%
  st_centroid() %>%
  st_coordinates() %>% 
  data.frame(address = pluto$Address, ., stringsAsFactors = FALSE) %>%
  tbl_df() %>%
  filter(!is.na(address))
```


#### Clean and merge data

```{r}
d = inner_join(
  mutate(nyc, address=tolower(address)), 
  mutate(pluto, address=tolower(address)),
  by="address"
)

manh_precincts = c(1,5,6,7,9,10,13,14,17,18,19,20,22,23,24,25,26,28,30,32,33,34)

d = filter(d, precinct %in% manh_precincts)

ggplot(d, aes(x=X, y=Y, color=as.factor(precinct))) +
  geom_point()
```


## Task 2 - Modeling

### Setup

```{r}
library(parallel)

  if (!file.exists("manh.Rdata")) {
    
    manh = st_read("/data/nyc_parking/nybb/nybb.shp", quiet=TRUE) %>%
      filter(BoroName == "Manhattan")
    
    manh_pts = mclapply(
      1:10,
      function(x) st_sample(manh, 1000),
      mc.cores = 10
    ) %>%
      unlist(recursive = FALSE) %>% 
      st_sfc() %>%
      st_set_crs(st_crs(manh))
     
    manh_xy = st_coordinates(manh_pts) %>% as.data.frame()
    
    save(manh, manh_pts, manh_xy, file="manh.Rdata")
    
  } else {
    load("manh.Rdata")
  }
```

```{r}
plot(st_geometry(manh), border="grey")
plot(manh_pts, add=TRUE, pch=16, cex=0.1)
```


### Logistic Regression

```{r}
d_lr = d %>% select(-address) %>% mutate(prec1 = as.factor(precinct == 1))

lr = glm(prec1 ~ poly(X,2)*poly(Y,2), family=binomial, data=d_lr)

pred = cbind(manh_xy, prob=predict(lr, newdata=manh_xy, type="response"))

ggplot(pred) +
  geom_point(aes(x=X,y=Y,color=prob), size=0.1, alpha=0.5)
```


### "Multiple" Logistic Regression

```{r}
library(purrr)

if (!file.exists("mlr_pred.Rdata")) {

  d_mlr = d %>% select(-address)
  precincts = d_mlr$precinct %>% unique() %>% sort()
  
  
  pb = dplyr::progress_estimated(length(precincts))
  pred = map(
    precincts,
    function(p) {
      pb$tick()$print()
      d_mlr %>%
        mutate(cur_prec = (precinct == p)) %>%
        {suppressWarnings(glm(cur_prec ~ poly(X,2)*poly(Y,2), family=binomial, data=.))} %>%
        predict(newdata=manh_xy, type="response")
    }
  )
  
  pred_index = do.call(cbind, pred) %>%
    apply(1, which.max)

  pred_precinct = precincts[pred_index]
  
  pred_df = cbind(manh_xy, precinct = pred_precinct)
  pred_sf = st_sf(precinct = pred_precinct, geometry = manh_pts)
  
  save(pred_df, pred_sf, file="mlr_pred.Rdata")
} else {
  load("mlr_pred.Rdata")
}
```

```{r}
## Prediction data frame

ggplot(pred_df) +
  geom_point(aes(x=X,y=Y,color=as.factor(precinct)), size=0.1, alpha=0.5) +
  guides(color = guide_legend(override.aes = list(size=2)))
```

```{r}
## Prediction sf

ggplot() +
  geom_sf(data=pred_sf, aes(color=as.factor(precinct)), size=0.1, alpha=0.5) +
  guides(color = guide_legend(override.aes = list(size=2)))
```

```{r}
## Predicting boundaries

pred_sf_mp = pred_sf %>%
  group_by(precinct) %>%
  summarize(geometry = list(st_cast(geometry,"MULTIPOINT")))

pred_boundary = pred_sf_mp %>% st_buffer(0.0013) %>% st_intersection(st_geometry(manh))

plot(mutate(pred_boundary, precinct=as.factor(precinct)))

ggplot() +
  geom_sf(data=pred_boundary, aes(fill=as.factor(precinct)), alpha=0.3)
```


```{r}
st_write(pred_boundary, "precincts.geojson", delete_dsn = TRUE, quiet=TRUE)
```


